#!/usr/bin/env node
/**
 * Generate the nginx security-header snippets from the built app.
 *
 * WHY THIS EXISTS
 *
 * The old policy was `script-src 'self' 'unsafe-inline'`. For this app that is
 * the same as having no script policy at all: vite-plugin-singlefile inlines
 * the ENTIRE bundle into index.html, so 'unsafe-inline' is not a small
 * concession for a bootstrap snippet — it is a blanket permit for every inline
 * script on the page, including any an attacker manages to inject. A CSP that
 * allows what it exists to prevent is worse than none, because it reads as
 * protection in an audit.
 *
 * The fix is hashes. The inline scripts are fixed at build time, so each one can
 * be pinned by its sha256 and 'unsafe-inline' dropped entirely. Browsers ignore
 * 'unsafe-inline' when a hash or nonce is present, but it is left out rather
 * than left in, so the intent is legible.
 *
 * Because the hashes change with every build, this runs AFTER `vite build` and
 * its output is generated, not hand-edited.
 *
 * Usage:  node deploy/gen-csp.mjs [path/to/index.html]
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const htmlPath = resolve(process.argv[2] || join(here, '..', 'dist', 'index.html'));

let html;
try {
  html = readFileSync(htmlPath, 'utf8');
} catch {
  console.error(`gen-csp: cannot read ${htmlPath}\n` +
    `Run \`VITE_API_URL=/ npm run build\` first, or pass the path explicitly.`);
  process.exit(1);
}

/**
 * Hash every inline block of a given tag.
 *
 * The content hashed must be EXACTLY what the browser sees between the tags —
 * no trimming, no newline normalisation. A single stray character produces a
 * hash that silently fails to match, and the symptom is a blank page rather
 * than an error pointing here.
 */
function hashesFor(tag) {
  // Skips tags carrying src=, which are external and covered by 'self'.
  const re = new RegExp(`<${tag}(?![^>]*\\bsrc=)[^>]*>([\\s\\S]*?)</${tag}>`, 'gi');
  const out = [];
  for (const m of html.matchAll(re)) {
    if (m[1] === '') continue;   // an empty block needs no hash
    out.push(`'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`);
  }
  return [...new Set(out)];
}

const scriptHashes = hashesFor('script');
if (scriptHashes.length === 0) {
  console.error('gen-csp: found no inline scripts — is this the built single-file index.html?');
  process.exit(1);
}

/**
 * style-src keeps 'unsafe-inline', deliberately.
 *
 * Not laziness: React writes `style={{…}}` as a style ATTRIBUTE, and CSP has no
 * hash mechanism that covers attributes ('unsafe-hashes' is for event handlers
 * and is itself widely discouraged). Hashing the one inline <style> block while
 * blocking attributes would break layout across the app for no security gain
 * that matters — CSS injection cannot execute script under this policy, because
 * script-src is now hash-pinned.
 */
const csp = (frameAncestors) => [
  `default-src 'self'`,
  `script-src 'self' ${scriptHashes.join(' ')}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: blob:`,
  `font-src 'self' data:`,
  `connect-src 'self'`,
  `worker-src 'self'`,
  `manifest-src 'self'`,
  `frame-ancestors ${frameAncestors}`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `object-src 'none'`,
].join('; ');

const common = `# GENERATED by deploy/gen-csp.mjs — do not edit by hand.
# Regenerate after every \`vite build\`; the script hashes change with the bundle.
#
# nginx drops ALL inherited add_header directives in any block that declares one
# of its own. That is why this file exists as an include rather than a set of
# server-level directives: every location that adds a header of its own must
# include it again, or it silently serves no security headers at all.

add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "no-referrer" always;
# Explicitly 0. The legacy XSS auditor this once enabled introduced its own
# vulnerabilities and is gone from current browsers; leaving it on is cargo cult.
add_header X-XSS-Protection "0" always;
add_header Permissions-Policy "geolocation=(self), camera=(), microphone=(), payment=(), usb=()" always;
`;

writeFileSync(join(here, 'security-headers.conf'), `${common}
# The app itself must never be framed.
add_header X-Frame-Options "DENY" always;
add_header Content-Security-Policy "${csp(`'none'`)}" always;
`);

writeFileSync(join(here, 'security-headers-embed.conf'), `${common}
# For /chat/ ONLY — the chatbot widget is designed to be embedded in an iframe
# on a builder's own website, so it is the one route that must be framable by
# anyone. X-Frame-Options is deliberately ABSENT: it has no "allow any origin"
# value, and sending DENY here would break every embed the product tells
# customers to paste.
add_header Content-Security-Policy "${csp('*')}" always;
`);

console.log(`gen-csp: read ${htmlPath}`);
console.log(`gen-csp: pinned ${scriptHashes.length} inline script hash(es)`);
scriptHashes.forEach(h => console.log(`  ${h}`));
console.log('gen-csp: wrote deploy/security-headers.conf and deploy/security-headers-embed.conf');
